language: python
python: 3.5
env:
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py32
  - TOX_ENV=py27
  - TOX_ENV=py26
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
deploy:
  provider: pypi
  user: netanelrevah
  password:
    secure: my_secure_password
  on:
    tags: true
    branch: develop